export interface Question {
  id: number;
  text: string;
  factorId: string;
}

export const scl90Questions: Question[] = [
  // 躯体化 (somatization)
  { id: 1, text: "头痛", factorId: "somatization" },
  { id: 2, text: "神经过敏，心中不踏实", factorId: "somatization" },
  { id: 3, text: "头脑中有不必要的想法或字句盘旋", factorId: "obsessive_compulsive" },
  { id: 4, text: "头昏或昏倒", factorId: "somatization" },
  { id: 5, text: "对异性的兴趣减退", factorId: "depression" },
  { id: 6, text: "对旁人责备求全", factorId: "interpersonal_sensitivity" },
  { id: 7, text: "感到别人能控制您的思想", factorId: "paranoid_ideation" },
  { id: 8, text: "责怪别人制造麻烦", factorId: "hostility" },
  { id: 9, text: "忘记性大", factorId: "obsessive_compulsive" },
  { id: 10, text: "担心自己的衣饰整齐及仪态的端正", factorId: "obsessive_compulsive" },
  { id: 11, text: "容易烦恼和激动", factorId: "anxiety" },
  { id: 12, text: "胸痛", factorId: "somatization" },
  { id: 13, text: "害怕空旷的场所或街道", factorId: "phobic_anxiety" },
  { id: 14, text: "感到自己的精力下降，活动减慢", factorId: "depression" },
  { id: 15, text: "想结束自己的生命", factorId: "depression" },
  { id: 16, text: "听到旁人听不到的声音", factorId: "psychoticism" },
  { id: 17, text: "发抖", factorId: "anxiety" },
  { id: 18, text: "感到大多数人都不可信任", factorId: "paranoid_ideation" },
  { id: 19, text: "胃口不好", factorId: "somatization" },
  { id: 20, text: "容易哭泣", factorId: "depression" },
  { id: 21, text: "同异性相处时感到害羞不自在", factorId: "interpersonal_sensitivity" },
  { id: 22, text: "感到受骗、中了圈套或有人想抓住您", factorId: "paranoid_ideation" },
  { id: 23, text: "无缘无故地突然感到害怕", factorId: "anxiety" },
  { id: 24, text: "自己不能控制地大发脾气", factorId: "hostility" },
  { id: 25, text: "怕单独出门", factorId: "phobic_anxiety" },
  { id: 26, text: "经常责怪自己", factorId: "depression" },
  { id: 27, text: "腰痛", factorId: "somatization" },
  { id: 28, text: "感到难以完成任务", factorId: "obsessive_compulsive" },
  { id: 29, text: "感到孤独", factorId: "depression" },
  { id: 30, text: "感到苦闷", factorId: "depression" },
  { id: 31, text: "过分担忧", factorId: "anxiety" },
  { id: 32, text: "对事物不感兴趣", factorId: "depression" },
  { id: 33, text: "感到害怕", factorId: "anxiety" },
  { id: 34, text: "我的感情容易受到伤害", factorId: "interpersonal_sensitivity" },
  { id: 35, text: "旁人能知道您的私下想法", factorId: "psychoticism" },
  { id: 36, text: "感到别人不理解您、不同情您", factorId: "interpersonal_sensitivity" },
  { id: 37, text: "感到人们对您不友好、不喜欢您", factorId: "interpersonal_sensitivity" },
  { id: 38, text: "做事必须做得很慢以保证做得正确", factorId: "obsessive_compulsive" },
  { id: 39, text: "心跳得很厉害", factorId: "somatization" },
  { id: 40, text: "恶心或胃部不舒服", factorId: "somatization" },
  { id: 41, text: "感到比不上他人", factorId: "interpersonal_sensitivity" },
  { id: 42, text: "肌肉酸痛", factorId: "somatization" },
  { id: 43, text: "感到有人在监视您、谈论您", factorId: "paranoid_ideation" },
  { id: 44, text: "难以入睡", factorId: "depression" },
  { id: 45, text: "做事必须反复检查", factorId: "obsessive_compulsive" },
  { id: 46, text: "难以做出决定", factorId: "obsessive_compulsive" },
  { id: 47, text: "怕乘电车、公共汽车、地铁或火车", factorId: "phobic_anxiety" },
  { id: 48, text: "呼吸有困难", factorId: "somatization" },
  { id: 49, text: "一阵阵发冷或发热", factorId: "somatization" },
  { id: 50, text: "因为感到害怕而避开某些东西、场合或活动", factorId: "phobic_anxiety" },
  { id: 51, text: "脑子变空了", factorId: "depression" },
  { id: 52, text: "身体发麻或刺痛", factorId: "somatization" },
  { id: 53, text: "喉咙有梗塞感", factorId: "somatization" },
  { id: 54, text: "感到前途没有希望", factorId: "depression" },
  { id: 55, text: "不能集中注意力", factorId: "obsessive_compulsive" },
  { id: 56, text: "感到身体的某一部分软弱无力", factorId: "somatization" },
  { id: 57, text: "感到紧张或容易紧张", factorId: "anxiety" },
  { id: 58, text: "感到手或脚发重", factorId: "somatization" },
  { id: 59, text: "想到死亡的事", factorId: "depression" },
  { id: 60, text: "吃得太多", factorId: "depression" },
  { id: 61, text: "当别人看着您或谈论您时感到不自在", factorId: "interpersonal_sensitivity" },
  { id: 62, text: "有一些不属于您自己的想法", factorId: "psychoticism" },
  { id: 63, text: "有想打人或伤害他人的冲动", factorId: "hostility" },
  { id: 64, text: "醒得太早", factorId: "depression" },
  { id: 65, text: "必须反复洗手、点数目或触摸某些东西", factorId: "obsessive_compulsive" },
  { id: 66, text: "睡得不稳不深", factorId: "depression" },
  { id: 67, text: "有想摔坏或破坏东西的冲动", factorId: "hostility" },
  { id: 68, text: "有一些别人没有的想法或念头", factorId: "psychoticism" },
  { id: 69, text: "感到对别人神经过敏", factorId: "interpersonal_sensitivity" },
  { id: 70, text: "在商店或电影院等人多的地方感到不自在", factorId: "phobic_anxiety" },
  { id: 71, text: "感到任何事情都很困难", factorId: "depression" },
  { id: 72, text: "一阵阵恐惧或惊恐", factorId: "anxiety" },
  { id: 73, text: "感到在公共场合吃东西很不舒服", factorId: "phobic_anxiety" },
  { id: 74, text: "经常与人争论", factorId: "hostility" },
  { id: 75, text: "单独一人时神经很紧张", factorId: "phobic_anxiety" },
  { id: 76, text: "别人对您的成绩没有做出恰当的评价", factorId: "interpersonal_sensitivity" },
  { id: 77, text: "即使和别人在一起也感到孤单", factorId: "depression" },
  { id: 78, text: "感到坐立不安、心神不定", factorId: "anxiety" },
  { id: 79, text: "感到自己没有什么价值", factorId: "depression" },
  { id: 80, text: "感到熟悉的东西变成陌生或不像是真的", factorId: "psychoticism" },
  { id: 81, text: "大叫或摔东西", factorId: "hostility" },
  { id: 82, text: "害怕会在公共场合昏倒", factorId: "phobic_anxiety" },
  { id: 83, text: "感到别人想占您的便宜", factorId: "paranoid_ideation" },
  { id: 84, text: "为一些有关性的想法而很苦恼", factorId: "obsessive_compulsive" },
  { id: 85, text: "您认为应该因为自己的过错而受到惩罚", factorId: "depression" },
  { id: 86, text: "感到要很快把事情做完", factorId: "anxiety" },
  { id: 87, text: "感到自己的身体有严重问题", factorId: "somatization" },
  { id: 88, text: "从未感到和其他人很亲近", factorId: "interpersonal_sensitivity" },
  { id: 89, text: "感到自己有罪", factorId: "depression" },
  { id: 90, text: "感到自己的脑子有毛病", factorId: "psychoticism" },

];